# Generated by Django 4.2.17 on 2024-12-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Servicecategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_service",
                    models.CharField(max_length=255, verbose_name="Nom du service"),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Categorie du service",
                "verbose_name_plural": "Categories du service",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Titre du service"
                    ),
                ),
                ("contenu", models.TextField(verbose_name="contenu")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="service_image",
                        verbose_name="Image du service",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date ajout du service"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="market.servicecategorie",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "AServices",
            },
        ),
    ]
