# Generated by Django 4.2.17 on 2024-12-16 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Service", "verbose_name_plural": "Services"},
        ),
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ville",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="ville"
                    ),
                ),
                (
                    "pays",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Pays"
                    ),
                ),
                (
                    "quartier",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Quartier ou secteur du vendeur",
                    ),
                ),
                (
                    "repere",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Point de référence du vendeur",
                    ),
                ),
                (
                    "contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Numéro de téléphone"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
        ),
    ]
