# Generated by Django 4.2.17 on 2024-12-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_adresse_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adresse",
            name="slug",
        ),
    ]
