# Generated by Django 4.2.17 on 2024-12-09 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("compte", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField(verbose_name="contenu message")),
                ("date", models.DateTimeField(verbose_name="Date heure")),
                ("lu", models.BooleanField(default=False)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_recu",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="message recu",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_envoye",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="message envoye",
                    ),
                ),
            ],
        ),
    ]
