# Generated by Django 4.2.17 on 2024-12-10 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("compte", "0002_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="response_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="compte.message",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(auto_now=True, verbose_name="Date heure"),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_envoye",
                to=settings.AUTH_USER_MODEL,
                verbose_name="message envoye par",
            ),
        ),
    ]
